### ISSUE TITLE
New version of pyjwkest breaks demo

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#1003]
The pyjwkest package has been updated, and has broken the oic version we currently depend on. This breaks our installation:
```
(ga4gh-env)jk@holly$ ga4gh_server                                                                                                                                                                                  
Traceback (most recent call last):
  File "/home/jk/tmp/ga4gh-demo/ga4gh-env/bin/ga4gh_server", line 7, in <module>
    from ga4gh.cli import server_main
  File "/home/jk/tmp/ga4gh-demo/ga4gh-env/local/lib/python2.7/site-packages/ga4gh/cli.py", line 21, in <module>
    import ga4gh.frontend as frontend
  File "/home/jk/tmp/ga4gh-demo/ga4gh-env/local/lib/python2.7/site-packages/ga4gh/frontend.py", line 21, in <module>
    import oic.oauth2
  File "/home/jk/tmp/ga4gh-demo/ga4gh-env/local/lib/python2.7/site-packages/oic/oauth2/__init__.py", line 9, in <module>
    from oic.oauth2.base import PBase
  File "/home/jk/tmp/ga4gh-demo/ga4gh-env/local/lib/python2.7/site-packages/oic/oauth2/base.py", line 7, in <module>
    from oic.utils.keyio import KeyJar
  File "/home/jk/tmp/ga4gh-demo/ga4gh-env/local/lib/python2.7/site-packages/oic/utils/keyio.py", line 18, in <module>
    from jwkest.jwk import rsa_load
  File "/home/jk/tmp/ga4gh-demo/ga4gh-env/local/lib/python2.7/site-packages/jwkest/jwk.py", line 13, in <module>
    from Crypto.PublicKey.RSA import RsaKey
ImportError: cannot import name RsaKey
```

We need to fix this ASAP, as our current version on pypi does not install. I suggest we pin to version
pyjwkest==1.0.1 as this is the currently known working version, and release an updated server.

We should investigate either pinning pyjwkest==1.0.1 or updating oic in master.

**Comment by jeromekelleher** [comment]
Closed in #1007.
