### ISSUE TITLE
searchFeaturesInDb not throwing correct exception

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#1135]
The searchFeaturesInDb  does not throw a BadPageTokenException when an invalid page token is passed (i.e., one that is not a valid integer). This causes an internal server error instead of flagging bad user input.

**Comment by david4096** [comment]
The error comes from `sqliteBackend.py`, which coerces the pagetoken to an int. The type needs to be guaranteed at a higher level since the pagetokens are strings, this is not caught by input validation.

```
[Thu Apr 21 16:29:53.919228 2016] [:error] [pid 28328:tid 140216056567552] Traceback (most recent call last):
[Thu Apr 21 16:29:53.919231 2016] [:error] [pid 28328:tid 140216056567552]   File "/srv/ga4gh/server/newserverenv/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
[Thu Apr 21 16:29:53.919233 2016] [:error] [pid 28328:tid 140216056567552]     rv = self.dispatch_request()
[Thu Apr 21 16:29:53.919235 2016] [:error] [pid 28328:tid 140216056567552]   File "/srv/ga4gh/server/newserverenv/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
[Thu Apr 21 16:29:53.919238 2016] [:error] [pid 28328:tid 140216056567552]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Apr 21 16:29:53.919240 2016] [:error] [pid 28328:tid 140216056567552]   File "/srv/ga4gh/server/newserverenv/lib/python2.7/site-packages/ga4gh-0.2.3.dev12+ng19af245.d20160420-py2.7.egg/ga4gh/frontend.py", line 562, in searchFeatures
[Thu Apr 21 16:29:53.919242 2016] [:error] [pid 28328:tid 140216056567552]     flask.request, app.backend.runSearchFeatures)
[Thu Apr 21 16:29:53.919244 2016] [:error] [pid 28328:tid 140216056567552]   File "/srv/ga4gh/server/newserverenv/lib/python2.7/site-packages/ga4gh-0.2.3.dev12+ng19af245.d20160420-py2.7.egg/ga4gh/frontend.py", line 432, in handleFlaskPostRequest
[Thu Apr 21 16:29:53.919247 2016] [:error] [pid 28328:tid 140216056567552]     return handleHttpPost(flaskRequest, endpoint)
[Thu Apr 21 16:29:53.919248 2016] [:error] [pid 28328:tid 140216056567552]   File "/srv/ga4gh/server/newserverenv/lib/python2.7/site-packages/ga4gh-0.2.3.dev12+ng19af245.d20160420-py2.7.egg/ga4gh/frontend.py", line 309, in handleHttpPost
[Thu Apr 21 16:29:53.919251 2016] [:error] [pid 28328:tid 140216056567552]     responseStr = endpoint(request.get_data())
[Thu Apr 21 16:29:53.919253 2016] [:error] [pid 28328:tid 140216056567552]   File "/srv/ga4gh/server/newserverenv/lib/python2.7/site-packages/ga4gh-0.2.3.dev12+ng19af245.d20160420-py2.7.egg/ga4gh/backend.py", line 955, in runSearchFeatures
[Thu Apr 21 16:29:53.919255 2016] [:error] [pid 28328:tid 140216056567552]     self.featuresGenerator)
[Thu Apr 21 16:29:53.919257 2016] [:error] [pid 28328:tid 140216056567552]   File "/srv/ga4gh/server/newserverenv/lib/python2.7/site-packages/ga4gh-0.2.3.dev12+ng19af245.d20160420-py2.7.egg/ga4gh/backend.py", line 695, in runSearchRequest
[Thu Apr 21 16:29:53.919259 2016] [:error] [pid 28328:tid 140216056567552]     for obj, nextPageToken in objectGenerator(request):
[Thu Apr 21 16:29:53.919262 2016] [:error] [pid 28328:tid 140216056567552]   File "/srv/ga4gh/server/newserverenv/lib/python2.7/site-packages/ga4gh-0.2.3.dev12+ng19af245.d20160420-py2.7.egg/ga4gh/datamodel/sequenceAnnotations.py", line 395, in getFeatures
[Thu Apr 21 16:29:53.919264 2016] [:error] [pid 28328:tid 140216056567552]     parentId=parentId, featureTypes=featureTypes)
[Thu Apr 21 16:29:53.919266 2016] [:error] [pid 28328:tid 140216056567552]   File "/srv/ga4gh/server/newserverenv/lib/python2.7/site-packages/ga4gh-0.2.3.dev12+ng19af245.d20160420-py2.7.egg/ga4gh/datamodel/sequenceAnnotations.py", line 135, in searchFeaturesInDb
[Thu Apr 21 16:29:53.919268 2016] [:error] [pid 28328:tid 140216056567552]     sql += sqliteBackend.limitsSql(pageToken, pageSize)
[Thu Apr 21 16:29:53.919270 2016] [:error] [pid 28328:tid 140216056567552]   File "/srv/ga4gh/server/newserverenv/lib/python2.7/site-packages/ga4gh-0.2.3.dev12+ng19af245.d20160420-py2.7.egg/ga4gh/sqliteBackend.py", line 48, in limitsSql
[Thu Apr 21 16:29:53.919279 2016] [:error] [pid 28328:tid 140216056567552]     start = int(pageToken)
[Thu Apr 21 16:29:53.919281 2016] [:error] [pid 28328:tid 140216056567552] ValueError: invalid literal for int() with base 10: 'string'
```

**Comment by dcolligan** [comment]
@david4096 can I close this?  this is pre-pb and pre-features cleanup

**Comment by david4096** [comment]
@dcolligan I don't think we can close based on Jerome's issue, searchFeaturesInDb doesn't throw that exception. The changes you've made may guard against the issue I posted.
