### ISSUE TITLE
Compound ID assumes names are ASCII

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#1187]
I tried adding a dataset with a non-ascii character (sql_repo branch).

```
(server-1)➜  server-1 git:(sql_repo) ✗ python repo_dev.py add-dataset l å 
Traceback (most recent call last):
  File "repo_dev.py", line 7, in <module>
    ga4gh.cli.repo_main()
  File "/Users/david/server-1/ga4gh/cli.py", line 2103, in repo_main
    RepoManager.runCommand(args)
  File "/Users/david/server-1/ga4gh/cli.py", line 2088, in runCommand
    runMethod()
  File "/Users/david/server-1/ga4gh/cli.py", line 1636, in addDataset
    dataset = datasets.Dataset(self._args.datasetName)
  File "/Users/david/server-1/ga4gh/datamodel/datasets.py", line 24, in __init__
    super(Dataset, self).__init__(None, localId)
  File "/Users/david/server-1/ga4gh/datamodel/__init__.py", line 427, in __init__
    self._compoundId = self.compoundIdClass(parentId, localId)
  File "/Users/david/server-1/ga4gh/datamodel/__init__.py", line 155, in __init__
    encodedLocalId = self.encode(str(localId))
  File "/Users/david/server-1/ga4gh/datamodel/__init__.py", line 197, in encode
    return idString.replace('"', '\\"')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```

**Comment by dcolligan** [comment]
Fixed in #1188
