### ISSUE TITLE
Attempting to delete in-use reference set results in stack trace

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/server#1226]
```
jk@holly$ python repo_dev.py remove-referenceset test.db NCBI37
Are you sure you want to delete the ReferenceSet 'NCBI37'? [y|N] y
repo_dev.py: error:

An internal error has occurred.  Please file a bug report at
https://github.com/ga4gh/server/issues
with all the relevant details, and the following stack trace.

Traceback (most recent call last):
  File "/scratch/jk/work/github/server/ga4gh/cli.py", line 2125, in repo_main
    RepoManager.runCommand(args)
  File "/scratch/jk/work/github/server/ga4gh/cli.py", line 2110, in runCommand
    runMethod()
  File "/scratch/jk/work/github/server/ga4gh/cli.py", line 1764, in removeReferenceSet
    self._confirmDelete("ReferenceSet", referenceSet.getLocalId(), func)
  File "/scratch/jk/work/github/server/ga4gh/cli.py", line 1567, in _confirmDelete
    func()
  File "/scratch/jk/work/github/server/ga4gh/cli.py", line 1763, in func
    self._updateRepo(self._repo.removeReferenceSet, referenceSet)
  File "/scratch/jk/work/github/server/ga4gh/cli.py", line 1581, in _updateRepo
    func(*args, **kwargs)
  File "/scratch/jk/work/github/server/ga4gh/datarepo.py", line 809, in removeReferenceSet
    cursor.execute(sql, (referenceSet.getId(),))
IntegrityError: FOREIGN KEY constraint failed
```
We should catch this error and raise a meaninful error message.

**Comment by dcolligan** [comment]
Fixed in #1342
