### ISSUE TITLE
tests/data/repo.db not tracked

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#1284]
Trying to get the tests up and running; got an error like this on a lot of the tests because `tests/data/repo.db` is not a tracked file and therefore not present on a new install:

```
======================================================================
FAIL: testServerStart (tests.end_to_end.test_server_start.TestServerStart)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dannyc/ga4gh/server/tests/end_to_end/test_server_start.py", line 23, in testServerStart
    app.start()
  File "/Users/dannyc/ga4gh/server/tests/end_to_end/server.py", line 68, in start
    self._waitForServerStartup()
  File "/Users/dannyc/ga4gh/server/tests/utils.py", line 150, in wrapper
    result = func(*args, **kwargs)
  File "/Users/dannyc/ga4gh/server/tests/utils.py", line 124, in wrapper
    while func(*args, **kwargs):
  File "/Users/dannyc/ga4gh/server/tests/end_to_end/server.py", line 145, in _waitForServerStartup
    assert False, failMessage
AssertionError: Server process unexpectedly died; stderr: Traceback (most recent call last):
  File "server_dev.py", line 7, in <module>
    ga4gh.cli.server_main()
  File "/Users/dannyc/ga4gh/server/ga4gh/cli.py", line 144, in server_main
    parsedArgs.config_file, parsedArgs.config, parsedArgs.port)
  File "/Users/dannyc/ga4gh/server/ga4gh/frontend.py", line 243, in configure
    dataRepository.open(datarepo.MODE_READ)
  File "/Users/dannyc/ga4gh/server/ga4gh/datarepo.py", line 338, in open
    self.assertExists()
  File "/Users/dannyc/ga4gh/server/ga4gh/datarepo.py", line 1208, in assertExists
    raise exceptions.RepoNotFoundException(self._dbFilename)
ga4gh.exceptions.RepoNotFoundException: Database file 'tests/data/repo.db' does not exist.  Either change the configuration to point to a valid file or create one using the repo manager.
```

**Comment by jeromekelleher** [comment]
You need to run ``scripts/build_test_data.py`` --- we got rid of the checked in DB as it was causing problems. It's up to devs to keep their test DB up to date.

Welcome back!

**Comment by dcolligan** [comment]
Thanks!

I guess we can close this then.
