### ISSUE TITLE
Bug In Get RNA Quantification

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#1359]
When the ID is not present in the map an unhandled exception is thrown.

```
Exception on / [GET]
Traceback (most recent call last):
  File "/Users/david/server-1/protobuftest/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/david/server-1/protobuftest/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/david/server-1/ga4gh/frontend.py", line 637, in searchExpressionLevels
    flask.request, app.backend.runSearchExpressionLevels)
  File "/Users/david/server-1/ga4gh/frontend.py", line 454, in handleFlaskPostRequest
    return handleHttpPost(flaskRequest, endpoint)
  File "/Users/david/server-1/ga4gh/frontend.py", line 329, in handleHttpPost
    responseStr = endpoint(request.get_data())
  File "/Users/david/server-1/ga4gh/backend.py", line 1213, in runSearchExpressionLevels
    self.expressionLevelsGenerator)
  File "/Users/david/server-1/ga4gh/backend.py", line 850, in runSearchRequest
    for obj, nextPageToken in objectGenerator(request):
  File "/Users/david/server-1/ga4gh/backend.py", line 777, in expressionLevelsGenerator
    rnaQuant = rnaQuantSet.getRnaQuantification(rnaQuantificationId)
  File "/Users/david/server-1/ga4gh/datamodel/rna_quantification.py", line 114, in getRnaQuantification
    return self._rnaQuantificationIdMap[rnaQuantificationId]
KeyError: u'WyJicmNhMSIsInJuYXNlcSIsIkVOQ0ZGNzg2R0tWIl0'
```

**Comment by kozbo** [comment]
Fixed by #1364, closing
