### ISSUE TITLE
G2P Features search bug

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#1379]
When I post a request to features/search with `name: "*"` using the compliance dataset I get an Internal Server Error.

```
http post localhost:8000/features/search featureSetId=WyJicmNhMSIsImdlbmNvZGV2MTkiXQ name="*"
```

**Comment by bwalsh** [comment]
@david4096  just saw this now...

**Comment by bwalsh** [comment]
Thanks for raising this.

**Comment by david4096** [comment]
Thanks for looking into it @bwalsh! Considering this fact, we might reconsider the notion that regular expressions can be implemented neutrally.

That being said, what is the expected behavior? Should we guard for it and move on?

**Comment by david4096** [comment]
Hey @bwalsh let me know if you think you'll have time to write a guard for this.

**Comment by bwalsh** [comment]
I should be able to get to this by Mon 10/31

**Comment by ejacox** [comment]
I cannot reproduce this error. I don't get any results though. I would expect the full set of results. If I don't include name, then I get the list of everything.
`http post localhost:8000/features/search featureSetId=WyJicmNhMSIsImdlbmNvZGV2MTkiXQ `

**Comment by david4096** [comment]
Here is the whole trace of the error:

```
Traceback (most recent call last):
  File "/home/david/git/server-1/env/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/david/git/server-1/env/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "ga4gh/server/frontend.py", line 604, in searchFeatures
    flask.request, app.backend.runSearchFeatures)
  File "ga4gh/server/frontend.py", line 467, in handleFlaskPostRequest
    return handleHttpPost(flaskRequest, endpoint)
  File "ga4gh/server/frontend.py", line 344, in handleHttpPost
    responseStr = endpoint(request.get_data())
  File "ga4gh/server/backend.py", line 911, in runSearchFeatures
    self.featuresGenerator)
  File "ga4gh/server/backend.py", line 568, in runSearchRequest
    for obj, nextPageToken in objectGenerator(request):
  File "ga4gh/server/backend.py", line 406, in featuresGenerator
    request, featureSet, parentId)
  File "ga4gh/server/paging.py", line 397, in __init__
    super(FeaturesIterator, self).__init__(request)
  File "ga4gh/server/paging.py", line 325, in __init__
    self._objectList = self._search()
  File "ga4gh/server/paging.py", line 418, in _search
    self._request.gene_symbol))
  File "ga4gh/server/datamodel/genotype_phenotype_featureset.py", line 146, in getFeatures
    for row in featuresResults.bindings:
  File "/home/david/git/server-1/env/local/lib/python2.7/site-packages/rdflib/query.py", line 178, in _get_bindings
    self._bindings += list(self._genbindings)
  File "/home/david/git/server-1/env/local/lib/python2.7/site-packages/rdflib/plugins/sparql/evaluate.py", line 350, in evalDistinct
    res = evalPart(ctx, part.p)
  File "/home/david/git/server-1/env/local/lib/python2.7/site-packages/rdflib/plugins/sparql/evaluate.py", line 236, in evalPart
    return evalProject(ctx, part)
  File "/home/david/git/server-1/env/local/lib/python2.7/site-packages/rdflib/plugins/sparql/evaluate.py", line 360, in evalProject
    res = evalPart(ctx, project.p)
  File "/home/david/git/server-1/env/local/lib/python2.7/site-packages/rdflib/plugins/sparql/evaluate.py", line 245, in evalPart
    return evalOrderBy(ctx, part)
  File "/home/david/git/server-1/env/local/lib/python2.7/site-packages/rdflib/plugins/sparql/evaluate.py", line 321, in evalOrderBy
    res = sorted(res, key=val, reverse=reverse)
  File "/home/david/git/server-1/env/local/lib/python2.7/site-packages/rdflib/plugins/sparql/evaluate.py", line 153, in evalFilter
    if _ebv(part.expr, c.forget(ctx)):
  File "/home/david/git/server-1/env/local/lib/python2.7/site-packages/rdflib/plugins/sparql/evalutils.py", line 50, in _ebv
    return EBV(expr.eval(ctx))
  File "/home/david/git/server-1/env/local/lib/python2.7/site-packages/rdflib/plugins/sparql/parserutils.py", line 194, in eval
    return self._evalfn(ctx)
  File "/home/david/git/server-1/env/local/lib/python2.7/site-packages/rdflib/plugins/sparql/operators.py", line 217, in Builtin_REGEX
    return Literal(bool(re.search(unicode(pattern), text, cFlag)))
  File "/home/david/git/server-1/env/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
  File "/home/david/git/server-1/env/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
error: nothing to repeat
127.0.0.1 - - [05/Dec/2016 15:46:14] "POST /features/search HTTP/1.1" 500 -
```

**Comment by david4096** [comment]
Any invalid regex will throw a 500, this probably affects description fields in g2p as well:

```
schemas git:(607_attributes) ✗ http post localhost:8000/features/search featureSetId=WyJicmNhMSIsImdhNGdoLWV4YW1wbGUtZGF0YS9jZ2QiXQ name="["
HTTP/1.0 500 INTERNAL SERVER ERROR
Content-Length: 61
Content-Type: application/json
Date: Tue, 06 Dec 2016 00:10:14 GMT
Server: Werkzeug/0.11.5 Python/2.7.12+

{
    "errorCode": 1277500761, 
    "message": "Internal Server Error"
}
```

**Comment by ejacox** [comment]
The previous query is backed by an RDF datastore. From what I understand, it doesn't accept query strings so name="*" is looking for a feature named '*', so no error. On the other hand, `http post localhost:8000/features/search featureSetId=WyJicmNhMSIsImdhNGdoLWNvbXBsaWFuY2UtZGF0YS9jZ2QiXQ name="*"` does cause an error. It is trying a python regular expression. However, '*' is invalid. The '.*' is valid python regex as noted before. Therefore, I am going to treat this issue as a bug in not validating the python expression and resolve it by returning a bad request error.
