### ISSUE TITLE
GET /variants/<id> not working with custom data

### ISSUE THREAD

**Issue by Welliton309** [ga4gh/server#1389]
I am testing GA4GH API with custom VCF data. The `GET /variants/<id>` method is not workig with this data. I think the problem is my data have many variants with no coverage. I am using the latest development version of this repository. The error code:

```
ERROR in app [/home/welliton/ga4gh-env/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py:1423]:
Exception on / [GET]
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/frontend.py", line 660, in getVariant
    id, flask.request, app.backend.runGetVariant)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/frontend.py", line 441, in handleFlaskGetRequest
    return handleHttpGet(id_, endpoint)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/frontend.py", line 355, in handleHttpGet
    responseStr = endpoint(id_)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/backend.py", line 633, in runGetVariant
    gaVariant = variantSet.getVariant(compoundId)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/datamodel/variants.py", line 700, in getVariant
    variant = self.convertVariant(record, self._callSetIds)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/datamodel/variants.py", line 684, in convertVariant
    self._convertGaCall(callSet, pysamCall))
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/datamodel/variants.py", line 651, in _convertGaCall
    call.genotype.extend(list(pysamCall.allele_indices))
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/protobuf-3.0.0b3-py2.7.egg/google/protobuf/internal/containers.py", line 275, in extend
    new_values = [self._type_checker.CheckValue(elem) for elem in elem_seq_iter]
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/protobuf-3.0.0b3-py2.7.egg/google/protobuf/internal/type_checkers.py", line 132, in CheckValue
    raise TypeError(message)
TypeError: None has type <type 'NoneType'>, but expected one of: (<type 'int'>, <type 'long'>)
Exception on / [GET]
Traceback (most recent call last):
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/frontend.py", line 660, in getVariant
    id, flask.request, app.backend.runGetVariant)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/frontend.py", line 441, in handleFlaskGetRequest
    return handleHttpGet(id_, endpoint)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/frontend.py", line 355, in handleHttpGet
    responseStr = endpoint(id_)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/backend.py", line 633, in runGetVariant
    gaVariant = variantSet.getVariant(compoundId)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/datamodel/variants.py", line 700, in getVariant
    variant = self.convertVariant(record, self._callSetIds)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/datamodel/variants.py", line 684, in convertVariant
    self._convertGaCall(callSet, pysamCall))
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/datamodel/variants.py", line 651, in _convertGaCall
    call.genotype.extend(list(pysamCall.allele_indices))
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/protobuf-3.0.0b3-py2.7.egg/google/protobuf/internal/containers.py", line 275, in extend
    new_values = [self._type_checker.CheckValue(elem) for elem in elem_seq_iter]
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/protobuf-3.0.0b3-py2.7.egg/google/protobuf/internal/type_checkers.py", line 132, in CheckValue
    raise TypeError(message)
TypeError: None has type <type 'NoneType'>, but expected one of: (<type 'int'>, <type 'long'>)
127.0.0.1 - - [26/Sep/2016 13:24:08] "GET /variants/WyJiaXBtZWQiLCJ2cyIsImJpcG1lZCIsIjEiLCIxNTExNyIsImI0NDBhYWRkNTMyODliNjkwMzc3YTA4YzkzZjgzY2UwIl0 HTTP/1.1" 500 -
```

Here a sample of VCF file that I am using:

```
GT:AD:DP:GQ:PL  0/0:2,0:2:6:0,6,73      ./.:0,0:0:.:0,0,0       0/0:2,0:2:6:0,6,58      1/1:0,3:3:9:92,9,0
```

_I have truncated the data due to sensible information._

**Comment by kozbo** [comment]
Hi @Welliton309, I have been looking at this stack trace. It is iterating through the calls for the Variant specified and it has come across an empty element. I am wondering if you get the same error when you use the searchVariants entry point? Note that this function call can be made such that any one (or all) of the calls can be returned. Perhaps we can use this as a way of tracking down the field that has pysam confused.

**Comment by Welliton309** [comment]
Hi @kozbo, thank you for answering. I did some tests with the custom VCF file. First I tested searchVariants as you suggested.

```
~/ga4gh-env/bin/ga4gh_client variants-search -r 1 -s 15000 -e 16000 http://localhost:8000/
```

The command above works fine and returns 5 variants with no information about any callset (as expected, I guess).

```
~/ga4gh-env/bin/ga4gh_client variants-search -c WyJiaXBtZWQiLCJ2cyIsImJpcG1lZCIsIkJQTTAwMDEiXQ \
-r 1 -s 15000 -e 16000 http://localhost:8000/
```

With the information of one callset, the command works fine too and returns the same 5 variants with information of the calls for the requested callset.

```
~/ga4gh-env/bin/ga4gh_client variants-search -c WyJiaXBtZWQiLCJ2cyIsImJpcG1lZCIsIkJQTTAwMDIiXQ \
-r 1 -s 15000 -e 16000 http://localhost:8000/
```

The same command but with another callset fails with the error below:

```
ERROR:ga4gh.client:500 {"errorCode": 1277500761, "message": "Internal Server Error"}
Traceback (most recent call last):
  File "/home/welliton/ga4gh-env/bin/ga4gh_client", line 11, in <module>
    load_entry_point('ga4gh==0.3.4.dev165+ng20c4094', 'console_scripts', 'ga4gh_client')()
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/cli/client.py", line 1659, in client_main
    raise exception
ga4gh.exceptions.RequestNonSuccessException: Url http://localhost:8000/variants/search?key=invalid had status_code 500
```

Server-side error:

```
127.0.0.1 - - [26/Sep/2016 20:33:01] "POST /datasets/search?key=invalid HTTP/1.1" 200 -
127.0.0.1 - - [26/Sep/2016 20:33:01] "POST /variantsets/search?key=invalid HTTP/1.1" 200 -
--------------------------------------------------------------------------------
ERROR in app [/home/welliton/ga4gh-env/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py:1423]:
Exception on / [GET]
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/frontend.py", line 568, in searchVariants
    flask.request, app.backend.runSearchVariants)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/frontend.py", line 461, in handleFlaskPostRequest
    return handleHttpPost(flaskRequest, endpoint)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/frontend.py", line 338, in handleHttpPost
    responseStr = endpoint(request.get_data())
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/backend.py", line 855, in runSearchVariants
    self.variantsGenerator)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/backend.py", line 562, in runSearchRequest
    for obj, nextPageToken in objectGenerator(request):
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/backend.py", line 352, in variantsGenerator
    request, variantSet)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/paging.py", line 69, in __init__
    self._initialiseIteration()
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/paging.py", line 90, in _initialiseIteration
    self._currentObject = next(self._searchIterator, None)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/datamodel/variants.py", line 738, in getVariants
    yield self.convertVariant(record, callSetIds)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/datamodel/variants.py", line 684, in convertVariant
    self._convertGaCall(callSet, pysamCall))
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/datamodel/variants.py", line 651, in _convertGaCall
    call.genotype.extend(list(pysamCall.allele_indices))
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/protobuf-3.0.0b3-py2.7.egg/google/protobuf/internal/containers.py", line 275, in extend
    new_values = [self._type_checker.CheckValue(elem) for elem in elem_seq_iter]
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/protobuf-3.0.0b3-py2.7.egg/google/protobuf/internal/type_checkers.py", line 132, in CheckValue
    raise TypeError(message)
TypeError: None has type <type 'NoneType'>, but expected one of: (<type 'int'>, <type 'long'>)
Exception on / [GET]
Traceback (most recent call last):
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/frontend.py", line 568, in searchVariants
    flask.request, app.backend.runSearchVariants)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/frontend.py", line 461, in handleFlaskPostRequest
    return handleHttpPost(flaskRequest, endpoint)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/frontend.py", line 338, in handleHttpPost
    responseStr = endpoint(request.get_data())
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/backend.py", line 855, in runSearchVariants
    self.variantsGenerator)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/backend.py", line 562, in runSearchRequest
    for obj, nextPageToken in objectGenerator(request):
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/backend.py", line 352, in variantsGenerator
    request, variantSet)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/paging.py", line 69, in __init__
    self._initialiseIteration()
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/paging.py", line 90, in _initialiseIteration
    self._currentObject = next(self._searchIterator, None)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/datamodel/variants.py", line 738, in getVariants
    yield self.convertVariant(record, callSetIds)
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/datamodel/variants.py", line 684, in convertVariant
    self._convertGaCall(callSet, pysamCall))
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/ga4gh-0.3.4.dev165+ng20c4094-py2.7.egg/ga4gh/datamodel/variants.py", line 651, in _convertGaCall
    call.genotype.extend(list(pysamCall.allele_indices))
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/protobuf-3.0.0b3-py2.7.egg/google/protobuf/internal/containers.py", line 275, in extend
    new_values = [self._type_checker.CheckValue(elem) for elem in elem_seq_iter]
  File "/home/welliton/ga4gh-env/lib/python2.7/site-packages/protobuf-3.0.0b3-py2.7.egg/google/protobuf/internal/type_checkers.py", line 132, in CheckValue
    raise TypeError(message)
TypeError: None has type <type 'NoneType'>, but expected one of: (<type 'int'>, <type 'long'>)
127.0.0.1 - - [26/Sep/2016 20:33:01] "POST /variants/search?key=invalid HTTP/1.1" 500 -
```

I investigated the VCF file and tested different genomic locations. This error occurs when one or more requested callsets have  `./.:0,0:0:.:0,0,0` or similar. 

----------------

Another example, the range 1:16280:16290 returns only one variant. The data of this variant:

```
GT:AD:DP:GQ:PGT:PID:PL  ./.:0,0:0:.:.:.:0,0,0   ./.:0,0:0:.:.:.:0,0,0   ./.:0,0:0:.:.:.:0,0,0   0/0:5,0:5:0:.:.:0,0,106
```

Only the 4th callset works. The first 3 callsets return the same error.

**Comment by kozbo** [comment]
Thanks @Welliton309, that looks to be some very useful testing. We will see if we can reproduce the problem here. Our software is guilty until proven innocent!

**Comment by Welliton309** [comment]
I am wondering if this error might be related to the data type determined for the `genotype` attribute of the `Call` class, which is `int32` ([reference](https://github.com/ga4gh/schemas/blob/master/src/main/proto/ga4gh/variants.proto#L121)). In the case of my custom VCF data, the genotype information are represented as `./.` when there is no coverage to call the variant.

**Comment by dcolligan** [comment]
pysam's `VariantRecordSample.allele_indices` [doc](https://github.com/pysam-developers/pysam/blob/68e966a158e3c9ee1bacb3460b71e820a97324e5/pysam/cbcf.pyx#L2921) says: "allele indices for called genotype, if present.  Otherwise None"

So it looks like what is happening is that pysam is returning (at least) one `None` value from the `allele_indices` invocation.  protobuf can't handle the None value, so it throws the error you're seeing.

This looks like a schema issue since AFAICT we don't have a way of representing missing alleles  (i.e. dots in the VCF file for the genotype; see section 1.4.2: https://samtools.github.io/hts-specs/VCFv4.2.pdf ) in the `genotype` attribute.  Perhaps an empty list could be interpreted that way, but if that's the intent it doesn't specify that case in the schema documentation.

**Comment by Welliton309** [comment]
Thank you for the explanation @dcolligan, it was very helpful. I did some tests and found a solution for the problem of variant calls with no coverage.

First, I replaced all `./.` to `0/0` in my custom VCF file. I did this to sure that there is no other problem with my data. It worked fine however this approach is not good enough because of the meaning of dots and zeroes are very different.

In the second approach, I cloned the [schemas](https://github.com/ga4gh/schemas) repository and changed [this line](https://github.com/ga4gh/schemas/blob/master/src/main/proto/ga4gh/variants.proto#L121) to:

```
google.protobuf.ListValue genotype = 3;
```

Then I compiled protobuf files using `protoc` version 3 and copied the update Python files server repository. It worked fine with no more errors. An example of output is showed below:

```
 ga4gh_client variants-search -c WyJiaXBtZWQiLCJ2cyIsImJpcG1lZCIsIkJQTTAwMDIiXQ -r chr1 -s 15900 -e 16000 http://localhost/ga4gh
```

```
WyJiaXBtZWQiLCJ2cyIsImJpcG1lZCIsImNocjEiLCIxNTkwMiIsIjViM2I5ODMzZmJmYjBjNDc1ZTBjYTE1ZTk1OWE1MDViIl0     WyJiaXBtZWQiLCJ2cyIsImJpcG1lZCJd        []      chr1    15902   15903   G       [u'GC'] ExcessHet=0.0428000018001;AC=2;FS=0.0;MLEAF=0.0189999993891;InbreedingCoeff=0.142900004983;AF=0.0379999987781;MLEAC=1;AN=52;SOR=2.83299994469;MQ=26.8600006104;QD=18.7099990845;DP=68;       WyJiaXBtZWQiLCJ2cyIsImJpcG1lZCIsIkJQTTAwMDIiXQ:values {
  null_value: NULL_VALUE
}
values {
  null_value: NULL_VALUE
}
:[]:{u'GQ': values {
  string_value: "None"
}
, u'AD': values {
  string_value: "0"
}
values {
  string_value: "0"
}
, u'DP': values {
  string_value: "0"
}
, u'PL': values {
  string_value: "0"
}
values {
  string_value: "0"
}
values {
  string_value: "0"
}
}:
```

On the client side, it worked fine because I am using a custom client written in R. The `NULL_VALUE` values of genotype were converted to NA ([missing data](https://stat.ethz.ch/R-manual/R-devel/library/base/html/NA.html)). However, I do not know if this solution is well suitable for the Python client or even for the main project.

**Comment by dcolligan** [comment]
Cool.  I recommend you file a issue referencing this thread in the schemas repository tracker, since it looks like the schema could use some modification to handle this case.

**Comment by david4096** [comment]
Upstream schema change [here](https://github.com/ga4gh/schemas/pull/735). @Welliton309 can you share the server changes you made?

**Comment by Welliton309** [comment]
I did:

```
protoc-3.1.0/bin/protoc -I protoc-3.1.0/include/ -I /home/welliton/GA4GH/schemas/src/main/proto --python_out=datamodel/ /home/welliton/GA4GH/schemas/src/main/proto/ga4gh/variants.proto
cp datamodel/ga4gh/variants_pb2.py server/ga4gh/
```

Where

- `/home/welliton/GA4GH/schemas/` is the schemas repository;
- `datamodel/` directory for protoc output;
- `server/ga4gh/` it the server directory.

I used protoc version 3.1.0.

The `variants_pb2.py` was the only file I changed.

**Comment by david4096** [comment]
Awful kind of you, thanks @Welliton309 !
