### ISSUE TITLE
remove-rnaquantificationset does not work

### ISSUE THREAD

**Issue by kozbo** [ga4gh/server#1423]
ga4gh-admin@ga4gh-demo:/srv/ga4gh0_6_0a8pre$ python repo_dev.py remove-rnaquantificationset repo.db 1kgenomes 1kg-rna
Are you sure you want to delete the RnaQuantificationSet '1kg-rna'? [y|N] y
repo_dev.py: error:

An internal error has occurred.  Please file a bug report at
https://github.com/ga4gh/server/issues
with all the relevant details, and the following stack trace.

Traceback (most recent call last):
  File "/srv/ga4gh0_6_0a8pre/ga4gh/cli/repomanager.py", line 1053, in repo_main
    RepoManager.runCommand(args)
  File "/srv/ga4gh0_6_0a8pre/ga4gh/cli/repomanager.py", line 1031, in runCommand
    runMethod()
  File "/srv/ga4gh0_6_0a8pre/ga4gh/cli/repomanager.py", line 544, in removeRnaQuantificationSet
    "RnaQuantificationSet", rnaQuantSet.getLocalId(), func)
  File "/srv/ga4gh0_6_0a8pre/ga4gh/cli/repomanager.py", line 73, in _confirmDelete
    func()
  File "/srv/ga4gh0_6_0a8pre/ga4gh/cli/repomanager.py", line 542, in func
    self._updateRepo(self._repo.removeRnaQuantification, rnaQuantSet)
AttributeError: 'SqlDataRepository' object has no attribute 'removeRnaQuantification'

**Comment by dcolligan** [comment]
Fixed in #1426
