### ISSUE TITLE
repomanager: List out of range error on readGroupIds when using "list" command

### ISSUE THREAD

**Issue by kozbo** [ga4gh/server#1472]
run this on the 1kgenomes server:
```
python repo_dev.py list /run/shm/1000Genomes/registries/repo.db
```
and see the following error
```
Traceback (most recent call last):
  File "/srv/ga4gh0_6_0a8pre/ga4gh/cli/repomanager.py", line 1053, in repo_main
    RepoManager.runCommand(args)
  File "/srv/ga4gh0_6_0a8pre/ga4gh/cli/repomanager.py", line 1031, in runCommand
    runMethod()
  File "/srv/ga4gh0_6_0a8pre/ga4gh/cli/repomanager.py", line 126, in list
    self._repo.printSummary()
  File "/srv/ga4gh0_6_0a8pre/ga4gh/datarepo.py", line 257, in printSummary
    quant._readGroupIds[0],
IndexError: list index out of range
```
Note that the list program displays all data until it gets to printing out the quantifications in the first quantification set, and then it fails.  

There are no readgroupIDs set because we don't have the RNA reads for this RNA data.

**Comment by david4096** [comment]
I added this to the current milestone, it should be easy to squash.
