### ISSUE TITLE
Master build failling

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#1566]
https://travis-ci.org/ga4gh/server/builds/200468009

Only one test is failing:
```
ERROR: test suite for <class 'tests.unit.test_oidc.TestFrontendOidc'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/util.py", line 470, in try_run
    return func()
  File "/home/travis/build/ga4gh/server/tests/unit/test_oidc.py", line 120, in setUpClass
    baseConfig="TestOidcConfig", extraConfig=config, port=8001)
  File "/home/travis/build/ga4gh/server/ga4gh/server/frontend.py", line 312, in configure
    app.oidcClient.provider_config(app.config['OIDC_PROVIDER'])
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/oic/oic/__init__.py", line 903, in provider_config
    pcr = response_cls().from_json(r.text)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/oic/oauth2/message.py", line 441, in from_json
    return self.from_dict(json.loads(txt))
  File "/opt/python/2.7.9/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/python/2.7.9/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/python/2.7.9/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

This is because the json string that it attempts to decode is:
```
<html>
<head>
<meta name="robots" content="noarchive" />
<meta name="googlebot" content="nosnippet" />
</head>
<body>
<div align=center>
<h3>Error. Page cannot be displayed. Please contact your service provider for more details.  (10)</h3>
</div>
</body>
</html>
```

Looking at `tests/unit/test_oidc.py`, it looks like we are relying upon an external service, `http://auth.com` to run this test, which is unfortunate.  Probably something changed with that external endpoint...

**Comment by ejacox** [comment]
I changed the OIDC provider to "https://accounts.example.com" in #1564 . This works. The website doesn't exist and it seems to be just a placeholder in the code, so it is not an external service.
