### ISSUE TITLE
Create backend exception framework

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#160]
The frontend has an exception hierarchy, but the backend doesn't really have any custom exception support at the moment.

Here's a good example of an exception we would like to catch (triggered by searching for a callSet inside a variantSet which doesn't have it: `python client_dev.py -O variants-search http://localhost:8000 -r 1 -c HG03279 -V 1000g_2011`):

```
Traceback (most recent call last):
  File "/Users/dannyc/ga4gh/new/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dannyc/ga4gh/new/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dannyc/ga4gh/server/ga4gh/frontend.py", line 174, in searchVariants
    return handleFlaskRequest(flask.request, app.backend.searchVariants)
  File "/Users/dannyc/ga4gh/server/ga4gh/frontend.py", line 116, in handleFlaskRequest
    return handleHttpPost(flaskRequest, endpoint)
  File "/Users/dannyc/ga4gh/server/ga4gh/frontend.py", line 81, in handleHttpPost
    responseStr = endpoint(request.get_data())
  File "/Users/dannyc/ga4gh/server/ga4gh/backend.py", line 93, in searchVariants
    self.variantsGenerator)
  File "/Users/dannyc/ga4gh/server/ga4gh/backend.py", line 65, in runSearchRequest
    for obj, nextPageToken in objectGenerator(request):
  File "/Users/dannyc/ga4gh/server/ga4gh/backend.py", line 141, in variantsGenerator
    for variant in iterator:
  File "/Users/dannyc/ga4gh/server/ga4gh/datamodel/variants.py", line 211, in getVariants
    cols = [col for name, col in self._sampleCols[callSetId]]
KeyError: u'HG03279'
```

Currently, this just bails and returns to the client:

```
{
  "errorCode": 7,
  "message": "Internal server error"
}
```

**Comment by dcolligan** [comment]
Fixed in #162
