### ISSUE TITLE
ga4gh_server unable to start

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#181]
I think this has to do with the new data directory layout
```
$ ga4gh_server wormtable ga4gh-example-data
Traceback (most recent call last):
  File "/Users/dannyc/ga4gh/new/bin/ga4gh_server", line 9, in <module>
    load_entry_point('ga4gh==0.1.0a1', 'console_scripts', 'ga4gh_server')()
  File "/Users/dannyc/ga4gh/new/lib/python2.7/site-packages/ga4gh-0.1.0a1-py2.7.egg/ga4gh/cli.py", line 72, in server_main
    args.dataDir, args.variantSetClass)
  File "/Users/dannyc/ga4gh/new/lib/python2.7/site-packages/ga4gh-0.1.0a1-py2.7.egg/ga4gh/backend.py", line 27, in __init__
    variantSetId, relativePath)
  File "/Users/dannyc/ga4gh/new/lib/python2.7/site-packages/ga4gh-0.1.0a1-py2.7.egg/ga4gh/datamodel/variants.py", line 69, in __init__
    self._table = wt.open_table(wtDir)
  File "/Users/dannyc/ga4gh/new/lib/python2.7/site-packages/wormtable.py", line 78, in open_table
    raise IOError(msg)
IOError: Wormtable home directory 'ga4gh-example-data/reads' not found or not in wormtable format.
```

Here is the current directory layout it can't deal with:

```
$ find ga4gh-example-data
ga4gh-example-data
ga4gh-example-data/reads
ga4gh-example-data/references
ga4gh-example-data/variants
ga4gh-example-data/variants/1000g_2011
ga4gh-example-data/variants/1000g_2011/index_CHROM+ID.db
ga4gh-example-data/variants/1000g_2011/index_CHROM+ID.xml
ga4gh-example-data/variants/1000g_2011/index_CHROM+POS.db
ga4gh-example-data/variants/1000g_2011/index_CHROM+POS.xml
ga4gh-example-data/variants/1000g_2011/table.dat
ga4gh-example-data/variants/1000g_2011/table.db
ga4gh-example-data/variants/1000g_2011/table.xml
ga4gh-example-data/variants/1000g_2013
ga4gh-example-data/variants/1000g_2013/index_CHROM+ID.db
ga4gh-example-data/variants/1000g_2013/index_CHROM+ID.xml
ga4gh-example-data/variants/1000g_2013/index_CHROM+POS.db
ga4gh-example-data/variants/1000g_2013/index_CHROM+POS.xml
ga4gh-example-data/variants/1000g_2013/table.dat
ga4gh-example-data/variants/1000g_2013/table.db
ga4gh-example-data/variants/1000g_2013/table.xml
```

**Comment by jeromekelleher** [comment]
I've just installed into a new virtualenv and can't reproduce this -- are you sure you've updated your code?

**Comment by dcolligan** [comment]
Hm, installing into a new virtualenv solved it for me, too.  My code was on the latest master... not sure what the difference between my two virtualenvs was...

**Comment by dcolligan** [comment]
Flask-Cors, pysam, and requests were the only packages that had different versions between my two virtualenvs... 

Guess it'll remain a mystery.
