### ISSUE TITLE
Vcf module missing causes test error

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#216]
Latest master's (68b6310673aede03df821efc778ef881503b2ff5) tests running on my local machine:

```
$ python scripts/run_tests.py
*** Running: "flake8 tests ga4gh scripts"
*** Running: "coverage erase"
*** Running: "nosetests --with-coverage --cover-package ga4gh --cover-inclusive --cover-min-percentage 80"
..E...........................................................................................
======================================================================
ERROR: Failure: ImportError (No module named vcf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dannyc/ga4gh/bug/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/dannyc/ga4gh/bug/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/dannyc/ga4gh/bug/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/dannyc/ga4gh/server/tests/datadriven/test_variants.py", line 11, in <module>
    import vcf
ImportError: No module named vcf
```

We should probably add the appropriate package to the requirements.txt file.  @jeromekelleher can you track this down?

**Comment by dcolligan** [comment]
Blah, nevermind, just needed to run `pip install -r requirements.txt` again.
