### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/server#306]
On navigating browser to /, the server spits out:
```
--------------------------------------------------------------------------------
ERROR in app [/Users/dannyc/ga4gh/bug/lib/python2.7/site-packages/flask/app.py:1423]:
Exception on /favicon.ico [GET]
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dannyc/ga4gh/bug/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dannyc/ga4gh/bug/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/dannyc/ga4gh/bug/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
127.0.0.1 - - [30/Mar/2015 12:53:39] "GET /favicon.ico HTTP/1.1" 404 -
```

**Comment by jeromekelleher** [comment]
Closed in #307.
