### ISSUE TITLE
/search/reads drops the last alignment in a BAM file

### ISSUE THREAD

**Issue by danvk** [ga4gh/server#488]
When I query [this toy BAM file][1] via the GA4GH server, I get back 14 alignments:

```
$ curl --data '{"readGroupIds":["pileup.js:chr17.1-250"]}' --header 'Content-Type: application/json' http://localhost:8000/v0.5.1/reads/search > /tmp/chr17.1-250.json | jq . | grep alignedSequence
      "alignedSequence": "ATTTAGCTAC",
      "alignedSequence": "CCCAATCATT",
      "alignedSequence": "TTAGATAAAGAGGATACTG",
      "alignedSequence": "AAAAGATAAGGGATAAA",
      "alignedSequence": "AGCTAA",
      "alignedSequence": "ATAGCTCTCAGC",
      "alignedSequence": "TAGGC",
      "alignedSequence": "CAGCGCCAT",
      "alignedSequence": "AGGTTTTATAAAACAAATAA",
      "alignedSequence": "GGTTTTATAAAACAAATAATT",
      "alignedSequence": "TTATAAAACAAATAATTAAGTCTACA",
      "alignedSequence": "CAAATAATTAAGTCTACAGAGCAAC",
      "alignedSequence": "AATAATTAAGTCTACAGAGCAACT",
      "alignedSequence": "TAATTAAGTCTACAGAGCAACTA",
```

When I view the same file with `samtools`, however, I get 15:

```
$ samtools view test-data/chr17.1-250.bam | cut -f10
ATTTAGCTAC
CCCAATCATT
TTAGATAAAGAGGATACTG
AAAAGATAAGGGATAAA
AGCTAA
ATAGCTCTCAGC
TAGGC
CAGCGCCAT
AGGTTTTATAAAACAAATAA
GGTTTTATAAAACAAATAATT
TTATAAAACAAATAATTAAGTCTACA
CAAATAATTAAGTCTACAGAGCAAC
AATAATTAAGTCTACAGAGCAACT
TAATTAAGTCTACAGAGCAACTA
TAATTAAGTCTACAGAAAAAAAA    <----
```

That last sequence, `TAATTAAGTCTACAGAAAAAAAA`, is not present in the ga4gh server response. It's the last alignment in the BAM file, which may be the source of the issue.

[1]: https://github.com/hammerlab/pileup.js/blob/c3d08997094741ce709892940a6bfbc0a6865948/test-data/chr17.1-250.bam

**Comment by jeromekelleher** [comment]
Thanks for this @danvk. When I run this example file against develop, I get another issue also. Client:
```
python client_dev.py -vv reads-search http://localhost:8000/current --readGroupIds=dataset2:danvk-bug-report:chr17.1-250
```
Server:
```
--------------------------------------------------------------------------------
ERROR in app [/home/jk/.local/lib/python2.7/site-packages/flask/app.py:1423]:
Exception on /current/reads/search [POST]
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jk/.local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jk/.local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jk/work/github/server/ga4gh/frontend.py", line 521, in searchReads
    version, flask.request, app.backend.searchReads)
  File "/home/jk/work/github/server/ga4gh/frontend.py", line 431, in handleFlaskPostRequest
    return handleHttpPost(flaskRequest, endpoint)
  File "/home/jk/work/github/server/ga4gh/frontend.py", line 297, in handleHttpPost
    responseStr = endpoint(request.get_data())
  File "/home/jk/work/github/server/ga4gh/backend.py", line 404, in searchReads
    self.readsGenerator)
  File "/home/jk/work/github/server/ga4gh/backend.py", line 376, in runSearchRequest
    for obj, nextPageToken in objectGenerator(request):
  File "/home/jk/work/github/server/ga4gh/backend.py", line 148, in next
    self._nextObject = next(self._searchIterator, None)
  File "/home/jk/work/github/server/ga4gh/datamodel/reads.py", line 246, in getReadAlignments
    yield self.convertReadAlignment(readAlignment)
  File "/home/jk/work/github/server/ga4gh/datamodel/reads.py", line 255, in convertReadAlignment
    ret.alignedQuality = list(read.query_qualities)
TypeError: 'NoneType' object is not iterable
127.0.0.1 - - [13/Jul/2015 11:25:52] "POST /current/reads/search?key=invalid HTTP/1.1" 500 -
```

We should add this file to our tests datasets, and push it through the datadriven tests.

**Comment by danvk** [comment]
Yes, I ran into that too. That BAM file is ultimately derived from one in the [samtools test suite][1]. If their BAM file exhibits the same issues, you should probably incorporate their version into your test suite instead.

[1]: https://github.com/samtools/samtools/blob/develop/test/dat/test_input_1_a.bam

**Comment by danvk** [comment]
I forked the `'NoneType object is not iterable` bug into a separate issue: https://github.com/ga4gh/server/issues/492

**Comment by dcolligan** [comment]
Querying the alignmentFile directly with pysam returns 15 results, unsurprisingly, so it's definitely a bug in our code.

**Comment by dcolligan** [comment]
Er, actually, I take that back... (not sure what I was doing before?) ... looks like a bug in pysam
```
$ ls
chr17.1-250.bam     chr17.1-250.bam.bai
$ python
>>> import pysam
>>> a = pysam.AlignmentFile('chr17.1-250.bam')
>>> len(list(a.fetch()))
14
```

**Comment by dcolligan** [comment]
Ah, disregard what I said before: that last read is unmapped, which is why we don't return it.  There are only 14 mapped reads in the file, so the server behavior is correct.

See https://github.com/ga4gh/server/issues/287
