### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by danvk** [ga4gh/server#492]
(forked from [this comment][1])

```
python client_dev.py -vv reads-search http://localhost:8000/current --readGroupIds=dataset2:danvk-bug-report:chr17.1-250
```

```
--------------------------------------------------------------------------------
ERROR in app [/home/jk/.local/lib/python2.7/site-packages/flask/app.py:1423]:
Exception on /current/reads/search [POST]
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jk/.local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jk/.local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jk/work/github/server/ga4gh/frontend.py", line 521, in searchReads
    version, flask.request, app.backend.searchReads)
  File "/home/jk/work/github/server/ga4gh/frontend.py", line 431, in handleFlaskPostRequest
    return handleHttpPost(flaskRequest, endpoint)
  File "/home/jk/work/github/server/ga4gh/frontend.py", line 297, in handleHttpPost
    responseStr = endpoint(request.get_data())
  File "/home/jk/work/github/server/ga4gh/backend.py", line 404, in searchReads
    self.readsGenerator)
  File "/home/jk/work/github/server/ga4gh/backend.py", line 376, in runSearchRequest
    for obj, nextPageToken in objectGenerator(request):
  File "/home/jk/work/github/server/ga4gh/backend.py", line 148, in next
    self._nextObject = next(self._searchIterator, None)
  File "/home/jk/work/github/server/ga4gh/datamodel/reads.py", line 246, in getReadAlignments
    yield self.convertReadAlignment(readAlignment)
  File "/home/jk/work/github/server/ga4gh/datamodel/reads.py", line 255, in convertReadAlignment
    ret.alignedQuality = list(read.query_qualities)
TypeError: 'NoneType' object is not iterable
127.0.0.1 - - [13/Jul/2015 11:25:52] "POST /current/reads/search?key=invalid HTTP/1.1" 500 -
```

[1]: https://github.com/ga4gh/server/issues/488#issuecomment-120886728

**Comment by dcolligan** [comment]
Fixed in #497
