### ISSUE TITLE
Local tests failing on fresh clone of repository

### ISSUE THREAD

**Issue by bwalsh** [ga4gh/server#501]
Hello.

Looking forward to contributing.  I'm planning on prototyping /search/genotypephenotype

As a developer, so that I can make changes with confidence I'm not breaking anything, I need to know the test baseline.

Using .travis.yml for guidance, I ran the nosetests on a fresh clone with the following results.

Is this the expected behavior?   

```
ERROR: testMultipleOidcClients (tests.end_to_end.test_oidc.TestOidc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ga4gh/server/tests/end_to_end/test_oidc.py", line 84, in testMultipleOidcClients
    key = getClientKey(serverUrl, 'diana', 'krall')
  File "/home/ga4gh/server/tests/end_to_end/test_oidc.py", line 44, in getClientKey
    tokenTag = (tag for tag in keyTree.iterdescendants()
StopIteration:
======================================================================
ERROR: testOidc (tests.end_to_end.test_oidc.TestOidc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ga4gh/server/tests/end_to_end/test_oidc.py", line 63, in testOidc
    key = getClientKey(serverUrl, 'diana', 'krall')
  File "/home/ga4gh/server/tests/end_to_end/test_oidc.py", line 44, in getClientKey
    tokenTag = (tag for tag in keyTree.iterdescendants()
StopIteration:
======================================================================
ERROR: testRunListRequest (tests.unit.test_client.TestRunRequest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ga4gh/server/tests/unit/test_client.py", line 239, in testRunListRequest
    mockGet.assert_called_twice_with(httpMethod, url, params=params)
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 715, in __getattr__
    raise AttributeError(name)
AttributeError: assert_called_twice_with

======================================================================
ERROR: testRunSearchRequest (tests.unit.test_client.TestRunRequest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ga4gh/server/tests/unit/test_client.py", line 174, in testRunSearchRequest
    mockPost.assert_called_twice_with(
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 715, in __getattr__
    raise AttributeError(name)
AttributeError: assert_called_twice_with

Name                          Stmts   Miss  Cover   Missing
-----------------------------------------------------------
ga4gh                             1      0   100%
ga4gh._protocol_definitions    1059     70    93%   40-41, 79-80, 254-255, 299-300, 395-396, 490-491, 520-521, 588-589, 618-619, 653-654, 686-687, 819-820, 909-910, 941-942, 977-978, 1017-1018, 1051-1052, 1091-1092, 1381-1382, 1427-1428, 1480-1481, 1644-1645, 1724-1725, 1803-1804, 1892-1893, 1972-1973, 2069-2070, 2184-2185, 2298-2299, 2386-2387, 2469-2470, 2562-2563, 2652-2653, 2899-2900, 2934-2935
ga4gh.avrotools                 302     35    88%   87, 190, 196, 215, 238-241, 262, 268-271, 277, 294, 297-301, 303, 344, 347, 353, 371, 386, 414, 423, 438, 454, 468, 477, 486, 492, 511-514
ga4gh.backend                   354     21    94%   30-31, 34-36, 42-47, 161-165, 304-305, 311-312, 325, 327, 562, 602
ga4gh.cli                       503    125    75%   50-55, 81, 83, 87, 121, 142, 161, 205, 244-256, 262-271, 304-305, 331-337, 350, 363-376, 385-394, 400-412, 425, 438, 451, 464, 477-482, 490, 503, 517-519, 530, 541, 551-567, 851, 873-874, 888, 892, 897-933
ga4gh.client                    127     14    89%   39, 54, 60, 70, 74-76, 80-82, 86, 90-92, 111
ga4gh.configtest                 24     12    50%   34-44, 51-54
ga4gh.converters                129     22    83%   106, 148-150, 153, 156, 159, 162, 185-188, 217-226, 229-233, 241-242
ga4gh.datamodel                 155     15    90%   26-27, 82, 98-99, 262-271
ga4gh.datamodel.datasets         84      2    98%   44, 80
ga4gh.datamodel.reads           183      0   100%
ga4gh.datamodel.references      118      0   100%
ga4gh.datamodel.variants        259      6    98%   45, 165, 196, 299, 425, 439
ga4gh.exceptions                141      5    96%   22-26
ga4gh.frontend                  329     20    94%   89, 92, 98, 106-109, 200, 202, 233, 269, 275, 338, 411, 424, 439, 470-471, 489, 763
ga4gh.protocol                  111      3    97%   125, 136, 200
ga4gh.serverconfig               42      0   100%
ga4gh.templates                   0      0   100%
-----------------------------------------------------------
TOTAL                          3921    350    91%
```

**Comment by dcolligan** [comment]
I'm guessing it's a library versions issue.  The last two will be fixed in #497.  Not sure about the first two.

**Comment by jeromekelleher** [comment]
Hi @bwalsh, great to have you here.  No, this is most certainly not the expected behaviour: we should have clean test passes, all the time.

I think @dcolligan is right, there's some library funniness going on here. Can you check what happens when you cd into ``oidc-provider`` and run ``./run.sh``? I think we're probably missing some library dependencies in requirements.txt. 

I'm not sure how the second two arise: @dcolligan, where did these come from?

**Comment by jeromekelleher** [comment]
#497 should make some of these issues go away @bwalsh. Can you update and try this again please?

**Comment by bwalsh** [comment]
Thanks.
Yes, that eliminated `assert_called_twice_with`.   
Digging a bit further to see if I can find more information on `tokenTag = (tag for tag in keyTree.iterdescendants()`

**Comment by jeromekelleher** [comment]
I have a feeling this relates to all the new low-level crypto libraries and stuff @bwalsh (see the last few issues opened) --- have you had any issues with pip install -r requirements.txt? What OS are you using?

**Comment by bwalsh** [comment]
Digging in a bit....
Added some debug statements and got some standard out.
Also added 
```
    if serverException.httpStatus == 500:
        raise RuntimeError(responseStr)
```

Looks like something is throwing a ServerError   (500)

pip freeze and os info also below

Thanks,

-b



```
    # Extract the key from the page
    print(keyPage.text)  # <------
    keyTree = html.fromstring(keyPage.text)
    print(keyTree) # <-------
    tokenMarker = 'Session Token '  # the token always appears after this text
    tokenTag = (tag for tag in keyTree.iterdescendants()
                if tag.text_content().startswith(tokenMarker)).next()
```


```
======================================================================
ERROR: testOidc (tests.end_to_end.test_oidc.TestOidc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ga4gh/server/tests/end_to_end/test_oidc.py", line 65, in testOidc
    key = getClientKey(serverUrl, 'diana', 'krall')
  File "/home/ga4gh/server/tests/end_to_end/test_oidc.py", line 46, in getClientKey
    tokenTag = (tag for tag in keyTree.iterdescendants()
StopIteration:
-------------------- >> begin captured stdout << ---------------------
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>RuntimeError: {&quot;errorCode&quot;: 1277500761, &quot;message&quot;: &quot;Internal Server Error&quot;} // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css" type="text/css">
    <!-- We need to make sure this has a favicon so that the debugger does not by
         accident trigger a request to /favicon.ico which might change the application
         state. -->
    <link rel="shortcut icon" href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script type="text/javascript">
      var TRACEBACK = 29056848,
          CONSOLE_MODE = false,
          EVALEX = true,
          SECRET = "1ZlsKqgYK83gVLbTemjQ";
    </script>
  </head>
  <body>
    <div class="debugger">
<h1>RuntimeError</h1>
<div class="detail">
  <p class="errormsg">RuntimeError: {&quot;errorCode&quot;: 1277500761, &quot;message&quot;: &quot;Internal Server Error&quot;}</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">

  <ul><li><div class="frame" id="frame-44114512">
  <h4>File <cite class="filename">"/usr/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1836</em>,
      in <code class="function">__call__</code></h4>
  <pre>return self.wsgi_app(environ, start_response)</pre>
</div>

<li><div class="frame" id="frame-22655888">
  <h4>File <cite class="filename">"/usr/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1820</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.make_response(self.handle_exception(e))</pre>
</div>

<li><div class="frame" id="frame-22656592">
  <h4>File <cite class="filename">"/usr/lib/python2.7/site-packages/flask_cors/extension.py"</cite>,
      line <em class="line">110</em>,
      in <code class="function">wrapped_function</code></h4>
  <pre>return cors_after_request(app.make_response(f(*args, **kwargs)))</pre>
</div>

<li><div class="frame" id="frame-22655952">
  <h4>File <cite class="filename">"/usr/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1403</em>,
      in <code class="function">handle_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-24703376">
  <h4>File <cite class="filename">"/usr/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1817</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.full_dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-24703440">
  <h4>File <cite class="filename">"/usr/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1477</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.handle_user_exception(e)</pre>
</div>

<li><div class="frame" id="frame-24703504">
  <h4>File <cite class="filename">"/usr/lib/python2.7/site-packages/flask_cors/extension.py"</cite>,
      line <em class="line">110</em>,
      in <code class="function">wrapped_function</code></h4>
  <pre>return cors_after_request(app.make_response(f(*args, **kwargs)))</pre>
</div>

<li><div class="frame" id="frame-24703568">
  <h4>File <cite class="filename">"/usr/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1379</em>,
      in <code class="function">handle_user_exception</code></h4>
  <pre>return handler(e)</pre>
</div>

<li><div class="frame" id="frame-24703632">
  <h4>File <cite class="filename">"/home/ga4gh/server/ga4gh/frontend.py"</cite>,
      line <em class="line">344</em>,
      in <code class="function">handleException</code></h4>
  <pre>raise RuntimeError(responseStr)</pre>
</div>
</ul>
  <blockquote>RuntimeError: {&quot;errorCode&quot;: 1277500761, &quot;message&quot;: &quot;Internal Server Error&quot;}</blockquote>
</div>

<div class="plain">
  <form action="/?__debugger__=yes&amp;cmd=paste" method="post">
    <p>
      <input type="hidden" name="language" value="pytb">
      This is the Copy/Paste friendly version of the traceback.  <span
      class="pastemessage">You can also paste this traceback into
      a <a href="https://gist.github.com/">gist</a>:
      <input type="submit" value="create paste"></span>
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask_cors/extension.py", line 110, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask_cors/extension.py", line 110, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1379, in handle_user_exception
    return handler(e)
  File "/home/ga4gh/server/ga4gh/frontend.py", line 344, in handleException
    raise RuntimeError(responseStr)
RuntimeError: {"errorCode": 1277500761, "message": "Internal Server Error"}</textarea>
  </form>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask_cors/extension.py", line 110, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask_cors/extension.py", line 110, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1379, in handle_user_exception
    return handler(e)
  File "/home/ga4gh/server/ga4gh/frontend.py", line 344, in handleException
    raise RuntimeError(responseStr)
RuntimeError: {"errorCode": 1277500761, "message": "Internal Server Error"}

-->

<Element html at 0x29ea1d0>

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
py.warnings: WARNING: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

py.warnings: WARNING: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

py.warnings: WARNING: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

py.warnings: WARNING: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

py.warnings: WARNING: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

py.warnings: WARNING: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

py.warnings: WARNING: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

py.warnings: WARNING: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

--------------------- >> end captured logging << ---------------------

```


PIP

```
# pip freeze
alabaster==0.7.6
avro==1.7.7
Babel==1.3
backports.ssl-match-hostname==3.4.0.2
Beaker==1.7.0
cffi==1.1.2
CherryPy==3.2.4
coverage==3.7.1
cryptography==0.9.3
docutils==0.12
enum34==1.0.4
flake8==2.3.0
Flask==0.10.1
Flask-Cors==2.0.1
funcsigs==0.4
future==0.14.3
guppy==0.1.10
html5lib==0.999999
humanize==0.5.1
idna==2.0
iniparse==0.4
ipaddress==1.0.13
isodate==0.5.1
itsdangerous==0.24
javapackages==1.0.0
Jinja2==2.7.3
lxml==3.2.1
Mako==1.0.1
MarkupSafe==0.23
mccabe==0.3.1
mock==1.1.3
ndg-httpsclient==0.4.0
nose==1.3.7
oic==0.7.6
pbr==1.3.0
pep8==1.6.2
pyaml==15.3.1
pyasn1==0.1.8
pycparser==2.14
pycrypto==2.6.1
pycurl==7.19.0
pyflakes==0.9.2
Pygments==2.0.2
pygpgme==0.3
pyjwkest==1.0.1
pyliblzma==0.5.3
pyOpenSSL==0.15.1
pyparsing==2.0.3
pysam==0.8.3
pytz==2015.4
PyVCF==0.6.7
pyxattr==0.5.1
PyYAML==3.11
rdflib==4.2.0
rdflib-jsonld==0.3
requests==2.7.0
six==1.9.0
snakefood==1.4
snowballstemmer==1.2.0
SPARQLWrapper==1.6.4
Sphinx==1.3.1
sphinx-rtd-theme==0.1.8
Twisted==15.2.1
urlgrabber==3.10
Werkzeug==0.10.4
yubico-client==1.9.1
yum-metadata-parser==1.1.4
zope.interface==4.1.2
```

docker client
```
# uname -a
Linux 590200bbf104 4.0.5-boot2docker #1 SMP Tue Jun 16 01:39:56 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

MacOS host
```
uname -a
Darwin RJHB282 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 20:23:44 PDT 2015; root:xnu-2782.20.48~8/RELEASE_X86_64 x86_64
```

**Comment by bwalsh** [comment]
Some additional logging found this:

### UpdateFailed: Remote key update from 'https://localhost:8443/static/jwks.json' failed.



```
ERROR: testMultipleOidcClients (tests.end_to_end.test_oidc.TestOidc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ga4gh/server/tests/end_to_end/test_oidc.py", line 86, in testMultipleOidcClients
    key = getClientKey(serverUrl, 'diana', 'krall')
  File "/home/ga4gh/server/tests/end_to_end/test_oidc.py", line 46, in getClientKey
    tokenTag = (tag for tag in keyTree.iterdescendants()
StopIteration:
-------------------- >> begin captured stdout << ---------------------
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>UpdateFailed: Remote key update from 'https://localhost:8443/static/jwks.json' failed. // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css" type="text/css">
    <!-- We need to make sure this has a favicon so that the debugger does not by
         accident trigger a request to /favicon.ico which might change the application
         state. -->
    <link rel="shortcut icon" href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script type="text/javascript">
      var TRACEBACK = 40521552,
          CONSOLE_MODE = false,
          EVALEX = true,
          SECRET = "qKCJv0jMbvR2KxHTxHxM";
    </script>
  </head>
  <body>
    <div class="debugger">
<h1>oic.utils.keyio.UpdateFailed</h1>
<div class="detail">
  <p class="errormsg">UpdateFailed: Remote key update from 'https://localhost:8443/static/jwks.json' failed.</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">

  <ul><li><div class="frame" id="frame-55583312">
  <h4>File <cite class="filename">"/usr/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1836</em>,
      in <code class="function">__call__</code></h4>
  <pre>return self.wsgi_app(environ, start_response)</pre>
</div>

<li><div class="frame" id="frame-34120592">
  <h4>File <cite class="filename">"/usr/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1820</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.make_response(self.handle_exception(e))</pre>
</div>

<li><div class="frame" id="frame-34121296">
  <h4>File <cite class="filename">"/usr/lib/python2.7/site-packages/flask_cors/extension.py"</cite>,
      line <em class="line">110</em>,
      in <code class="function">wrapped_function</code></h4>
  <pre>return cors_after_request(app.make_response(f(*args, **kwargs)))</pre>
</div>

<li><div class="frame" id="frame-34120656">
  <h4>File <cite class="filename">"/usr/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1403</em>,
      in <code class="function">handle_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-36172240">
  <h4>File <cite class="filename">"/usr/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1817</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.full_dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-36172304">
  <h4>File <cite class="filename">"/usr/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1477</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.handle_user_exception(e)</pre>
</div>

<li><div class="frame" id="frame-36172368">
  <h4>File <cite class="filename">"/usr/lib/python2.7/site-packages/flask_cors/extension.py"</cite>,
      line <em class="line">110</em>,
      in <code class="function">wrapped_function</code></h4>
  <pre>return cors_after_request(app.make_response(f(*args, **kwargs)))</pre>
</div>

<li><div class="frame" id="frame-36172432">
  <h4>File <cite class="filename">"/usr/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1379</em>,
      in <code class="function">handle_user_exception</code></h4>
  <pre>return handler(e)</pre>
</div>

<li><div class="frame" id="frame-36172496">
  <h4>File <cite class="filename">"/home/ga4gh/server/ga4gh/frontend.py"</cite>,
      line <em class="line">344</em>,
      in <code class="function">handleException</code></h4>
  <pre>raise exception</pre>
</div>
</ul>
  <blockquote>UpdateFailed: Remote key update from 'https://localhost:8443/static/jwks.json' failed.</blockquote>
</div>

<div class="plain">
  <form action="/?__debugger__=yes&amp;cmd=paste" method="post">
    <p>
      <input type="hidden" name="language" value="pytb">
      This is the Copy/Paste friendly version of the traceback.  <span
      class="pastemessage">You can also paste this traceback into
      a <a href="https://gist.github.com/">gist</a>:
      <input type="submit" value="create paste"></span>
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask_cors/extension.py", line 110, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask_cors/extension.py", line 110, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1379, in handle_user_exception
    return handler(e)
  File "/home/ga4gh/server/ga4gh/frontend.py", line 344, in handleException
    raise exception
UpdateFailed: Remote key update from 'https://localhost:8443/static/jwks.json' failed.</textarea>
  </form>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask_cors/extension.py", line 110, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask_cors/extension.py", line 110, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1379, in handle_user_exception
    return handler(e)
  File "/home/ga4gh/server/ga4gh/frontend.py", line 344, in handleException
    raise exception
UpdateFailed: Remote key update from 'https://localhost:8443/static/jwks.json' failed.

-->

<Element html at 0x14fdcb0>

--------------------- >> end captured stdout << ----------------------
```

**Comment by bwalsh** [comment]
Hmm.  Upgraded from python 2.7.5 to python 2.7.10, still get the same error `UpdateFailed: Remote key update from 'https://localhost:8443/static/jwks.json' failed.`

**Comment by bwalsh** [comment]
Found the problem.

After running the `oidc-provider` in standalone mode. I found that it was returning a 500 error to 
`curl -vk https://localhost:8443/static/jwks.json`.  In turn that 500 error was caused by:

```
# server/oidc-provider/simple_op/src/provider/server.py:149
            content_type, encoding = mimetypes.guess_type(full_path)
>> returns (None,None)

```


digging in a bit, it seems that mimetypes known files assumes that the OS knows about mimetypes


```
>>> import mimetypes
>>> mimetypes.knownfiles
['/etc/mime.types', '/etc/httpd/mime.types', '/etc/httpd/conf/mime.types', '/etc/apache/mime.types', '/etc/apache2/mime.types', '/usr/local/etc/httpd/conf/mime.types', '/usr/local/lib/netscape/mime.types', '/usr/local/etc/httpd/conf/mime.types', '/usr/local/etc/mime.types']

### in mimetypes.py

knownfiles = [
    "/etc/mime.types",
    "/etc/httpd/mime.types",                    # Mac OS X
    "/etc/httpd/conf/mime.types",               # Apache
    "/etc/apache/mime.types",                   # Apache 1
    "/etc/apache2/mime.types",                  # Apache 2
    "/usr/local/etc/httpd/conf/mime.types",
    "/usr/local/lib/netscape/mime.types",
    "/usr/local/etc/httpd/conf/mime.types",     # Apache 1.2
    "/usr/local/etc/mime.types",                # Apache 1.3
    ]


```


_ my trouble was that the centos:7  Dockerimage I was using has none of those set _

Workaround: populate /etc/mime.types from `http://svn.apache.org/viewvc/httpd/httpd/branches/2.2.x/docs/conf/mime.types?view=annotate`

**Comment by jeromekelleher** [comment]
Thanks for digging in to this @bwalsh. This is unsettling --- do you think there's a way we can fail earlier and with a more informative error if this occurs again?

**Comment by bwalsh** [comment]
added a test in the `g2p` branch
