### ISSUE TITLE
Documentation for OpenID needs updating

### ISSUE THREAD

**Issue by david4096** [ga4gh/server#992]
After running this line: `python server_dev.py -c LocalOidConfig`

```
(server-1)➜  server-1 git:(master) ✗ python server_dev.py --config LocalOidConfig
/Users/david/server-1/server-1/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "server_dev.py", line 7, in <module>
    ga4gh.cli.server_main()
  File "/Users/david/server-1/ga4gh/cli.py", line 89, in server_main
    parsedArgs.config_file, parsedArgs.config, parsedArgs.port)
  File "/Users/david/server-1/ga4gh/frontend.py", line 233, in configure
    app.oidcClient.provider_config(app.config['OIDC_PROVIDER'])
  File "/Users/david/server-1/server-1/lib/python2.7/site-packages/oic/oic/__init__.py", line 915, in provider_config
    self.handle_provider_config(pcr, issuer, keys, endpoints)
  File "/Users/david/server-1/server-1/lib/python2.7/site-packages/oic/oic/__init__.py", line 873, in handle_provider_config
    pcr)
oic.exception.IssuerMismatch: 'https://localhost:8443/' != 'https://eduroam-169-233-228-52.ucsc.edu:8443/'
```

My DNS name doesn't match the hardcoded localhost.

**Comment by jeromekelleher** [comment]
Is this documentation or problem or a bug in the code?

**Comment by david4096** [comment]
I'm not sure since I haven't seen it work properly. The documentation wasn't enough to get it started at the very least so I assumed there was some other configuration setting I had missed.

**Comment by skeenan** [comment]
@bartgrantham  created a beacon server, using the refserver and openID [docs](https://github.com/Genecloud/simplebeacon). Might be of some use in helping debug...
